<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'VendorNamespace\\QuxClass' => $vendorDir . '/QuxClass.php',
);
