<?php

// autoload_psr4.php @generated by Composer

$vendorDir = __DIR__ . '/vendor';
$baseDir = __DIR__ . '/base';

return array(
    'VendorNamespace\\' => array($vendorDir),
    'BaseNamespace\\' => array($baseDir),
);
