<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    'app_foo_bar' => [['id'], ['_controller' => 'App\\Foo\\BarController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/foo/bar']], [], [], []],
    'App\Foo\BarController::index' => [['id'], ['_controller' => 'App\\Foo\\BarController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/foo/bar']], [], [], []],
];
